### PR TITLE
Wrapper for L-BFGS

### PR DESCRIPTION
**Pull request by rth**
At attempt to wrap LBFGS for https://github.com/argmin-rs/argmin/issues/10

In the end, we would want to have several optimizer exposed in Python so this PR shouldn't shouldn't remove the Landweber but for now I'm just trying to make sure I understand how things work.

This commit dates from several month ago, trying to get back to it now.

### CODE REVIEW

**Comment by rth** [comment]
Sounds like there is an issue with linking BLAS in either ndarray or ndarray-linalg,
```
$ python setup.py develop
$ pytest argmin
____________________________________________ ERROR collecting argmin/tests/test_argmin.py _____________________________________________
ImportError while importing test module '/home/rth/src/pyargmin/argmin/tests/test_argmin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
argmin/__init__.py:1: in <module>
    from ._lib import *  # noqa
E   ImportError: /home/rth/src/pyargmin/argmin/_lib.cpython-38-x86_64-linux-gnu.so: 
       undefined symbol: cblas_ddot
```

Will try to investigate later.

**Comment by rth** [comment]
@stefan-k Please let me know if you have availability to review or if I should go ahead and merge this given that all this is still very experimental.

The next step would be to make `PyExecutor` and `executor` to accept multiple solvers (and of course there are plenty other documentation and Python function usability improvements possible).

**Comment by stefan-k** [comment]
Hi @rth, great to have you back :)

You can go ahead with merging as you wish. I agree that the entire project is still very experimental and it is probably the best to just explore the available options.

**Comment by rth** [comment]
Thanks @stefan-k ! Yeah, I meant to look into this for a while. Haven't realized that 8 months passed by :)

Merging then.

**Pull request merged**
